// Loads the gitignored .env.local and exposes the validated runtime secrets.
// Throwaway TESTNET keys only — generated by `pnpm setup`, never committed.
import "dotenv/config";
import { config as loadEnv } from "dotenv";
import { existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import type { Hex } from "viem";

const here = dirname(fileURLToPath(import.meta.url));
const envLocal = resolve(here, "..", ".env.local");

// .env.local (gitignored, real keys) takes precedence over any process env.
if (existsSync(envLocal)) loadEnv({ path: envLocal, override: true });

function requireHexKey(name: string): Hex {
  const v = process.env[name];
  if (!v || !/^0x[0-9a-fA-F]{64}$/.test(v)) {
    throw new Error(
      `${name} is missing or not a 32-byte hex key. Run \`pnpm setup\` to generate testnet keys into .env.local.`
    );
  }
  return v as Hex;
}

function requireAddress(name: string): `0x${string}` {
  const v = process.env[name];
  if (!v || !/^0x[0-9a-fA-F]{40}$/.test(v)) {
    throw new Error(`${name} is missing or not a 20-byte address.`);
  }
  return v as `0x${string}`;
}

export const ENV = {
  agentPrivateKey: requireHexKey("AGENT_PRIVATE_KEY"),
  attestorPrivateKey: requireHexKey("ATTESTOR_PRIVATE_KEY"),
  creatorAddress: requireAddress("CREATOR_ADDRESS"),
  viewPrice: process.env.VIEW_PRICE ?? "$0.01",
  port: Number(process.env.PORT ?? 8787),
  // The server calls its own creator endpoint as the buyer; override if proxied.
  selfUrl: process.env.SELF_URL ?? `http://localhost:${process.env.PORT ?? 8787}`,
};
