// Loads the gitignored .env.local and exposes the validated runtime secrets.
// Throwaway TESTNET keys only — generated by `pnpm setup`, never committed.
import "dotenv/config";
import { config as loadEnv } from "dotenv";
import { existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import type { Hex } from "viem";

const here = dirname(fileURLToPath(import.meta.url));
const envLocal = resolve(here, "..", ".env.local");

// .env.local (gitignored, real keys) takes precedence over any process env.
if (existsSync(envLocal)) loadEnv({ path: envLocal, override: true });

function requireHexKey(name: string): Hex {
  const v = process.env[name];
  if (!v || !/^0x[0-9a-fA-F]{64}$/.test(v)) {
    throw new Error(
      `${name} is missing or not a 32-byte hex key. Run \`pnpm setup\` to generate testnet keys into .env.local.`
    );
  }
  return v as Hex;
}

function requireAddress(name: string): `0x${string}` {
  const v = process.env[name];
  if (!v || !/^0x[0-9a-fA-F]{40}$/.test(v)) {
    throw new Error(`${name} is missing or not a 20-byte address.`);
  }
  return v as `0x${string}`;
}

export const ENV = {
  agentPrivateKey: requireHexKey("AGENT_PRIVATE_KEY"),
  attestorPrivateKey: requireHexKey("ATTESTOR_PRIVATE_KEY"),
  creatorAddress: requireAddress("CREATOR_ADDRESS"),
  // Lets the creator read its own Gateway balance and withdraw credited earnings on-chain.
  creatorPrivateKey: requireHexKey("CREATOR_PRIVATE_KEY"),
  viewPrice: process.env.VIEW_PRICE ?? "$0.01",
  port: Number(process.env.PORT ?? 8787),
  // The server calls its own creator endpoint as the buyer; override if proxied.
  selfUrl: process.env.SELF_URL ?? `http://localhost:${process.env.PORT ?? 8787}`,
  // Circle Programmable Wallets (Developer-Controlled). Optional: only needed for the creator's
  // Circle-managed treasury wallet. Both come from the Circle Developer Console — the API key you
  // generate there, plus an entity secret you register via `pnpm circle:gen` / `pnpm circle:register`.
  circleApiKey: process.env.CIRCLE_API_KEY?.trim() || undefined,
  circleEntitySecret: process.env.CIRCLE_ENTITY_SECRET?.trim() || undefined,
  // Comma-separated list of browser origins allowed to call this backend (e.g.
  // "https://app.arclight.xyz,https://arclight.xyz"). Empty means allow-all, which is
  // fine for local dev but should always be set in a public deployment.
  allowedOrigins: (process.env.ALLOWED_ORIGINS ?? "")
    .split(",")
    .map((s) => s.trim())
    .filter(Boolean),
  // Fixed-window rate limits (per client IP). Overridable via env for tuning in production.
  rateWindowMs: Number(process.env.RATE_WINDOW_MS ?? 60_000),
  rateMaxRead: Number(process.env.RATE_MAX_READ ?? 120), // GET/read endpoints per window
  rateMaxWrite: Number(process.env.RATE_MAX_WRITE ?? 20), // money-moving writes per window
};

// True only when both Circle Console credentials are present, so the treasury feature can light up.
export const HAS_CIRCLE_CREDS = Boolean(ENV.circleApiKey && ENV.circleEntitySecret);
