// One-time local setup. Generates THROWAWAY testnet keys for the agent / creator / attestor and
// writes them to .env.local (gitignored). Private keys are written to that file only — never printed
// to the console or committed. Re-running is refused if .env.local already exists, so you never
// clobber keys you have already funded or registered on-chain.
import { generatePrivateKey, privateKeyToAccount } from "viem/accounts";
import { existsSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { CONTRACTS } from "./config.js";

const here = dirname(fileURLToPath(import.meta.url));
const envLocal = resolve(here, "..", ".env.local");

if (existsSync(envLocal)) {
  console.error(
    "Refusing to overwrite existing .env.local.\n" +
      "Delete it manually if you really want fresh keys (you'll need to re-fund and re-register the attestor)."
  );
  process.exit(1);
}

const agentKey = generatePrivateKey();
const creatorKey = generatePrivateKey();
const attestorKey = generatePrivateKey();

const agent = privateKeyToAccount(agentKey);
const creator = privateKeyToAccount(creatorKey);
const attestor = privateKeyToAccount(attestorKey);

const contents = `# Arclight backend — generated by \`pnpm setup\`. THROWAWAY TESTNET KEYS. Gitignored. Do not commit.
AGENT_PRIVATE_KEY=${agentKey}
CREATOR_ADDRESS=${creator.address}
# Creator's private key kept here so the same wallet can convert/yield/bridge later in the demo.
CREATOR_PRIVATE_KEY=${creatorKey}
ATTESTOR_PRIVATE_KEY=${attestorKey}
VIEW_PRICE=$0.01
PORT=8787
`;

writeFileSync(envLocal, contents, { encoding: "utf8", mode: 0o600 });

console.log("Wrote .env.local (gitignored). Private keys are in that file only.\n");
console.log("Addresses (safe to share — fund these on Arc testnet):");
console.log(`  AGENT    ${agent.address}`);
console.log(`  CREATOR  ${creator.address}`);
console.log(`  ATTESTOR ${attestor.address}`);
console.log("\nNext steps:");
console.log("  1. Fund the AGENT with testnet USDC (and a little gas) from the Arc faucet.");
console.log("  2. Deposit USDC into the agent's Circle Gateway balance:  pnpm deposit 5");
console.log("  3. Register the ATTESTOR on-chain so its signatures are trusted:");
console.log(`       cast send ${CONTRACTS.ProofOfView} 'setAttestor(address)' ${attestor.address} \\`);
console.log("         --rpc-url <arc-testnet-rpc> --account <owner-keystore>");
console.log("  4. `pnpm balance` to confirm the agent's Gateway balance, then `pnpm dev`.");
