// SPDX-License-Identifier: MIT
pragma solidity ^0.8.30;

import {Test} from "forge-std/Test.sol";
import {Groth16Verifier} from "../../src/zk/Groth16Verifier.sol";
import {ZkViewPrivacyVerifier} from "../../src/zk/ZkViewPrivacyVerifier.sol";
import {ProofOfView} from "../../src/oracle/ProofOfView.sol";
import {IProofOfView} from "../../src/interfaces/IProofOfView.sol";
import {IViewPrivacyVerifier} from "../../src/interfaces/IViewPrivacyVerifier.sol";

/**
 * @title ZkViewPrivacyVerifierTest
 * @author Malek Sharabi
 * @notice Proves the privacy layer end to end with a real Groth16 proof generated by our circom circuit. The fixture
 * below was produced by circuits/gen_proof.js for a viewer in campaign 42 and epoch 7, with public signals in the
 * circuit order [commitment, nullifier, campaignId, epoch]. This is the demonstration of Configurable Privacy: the
 * chain confirms a genuine unique viewer without ever learning who they are.
 */
contract ZkViewPrivacyVerifierTest is Test {
    Groth16Verifier internal groth16;
    ZkViewPrivacyVerifier internal verifier;
    ProofOfView internal oracle;

    address internal owner = makeAddr("owner");
    address internal splitter = makeAddr("splitter");
    address internal advertiser = makeAddr("advertiser");
    address internal creator = makeAddr("creator");

    address internal attestor;
    uint256 internal attestorKey;

    // Fixture from circuits/gen_proof.js. Public signals [commitment, nullifier, campaignId, epoch].
    uint256 internal constant COMMITMENT =
        2_864_389_652_507_728_666_782_898_074_924_898_615_246_276_780_518_167_362_510_075_982_111_100_849_653;
    uint256 internal constant NULLIFIER =
        6_453_744_564_484_786_948_487_995_587_499_660_070_229_130_905_991_604_071_472_631_485_553_023_418_182;
    uint256 internal constant CAMPAIGN_ID = 42;
    uint256 internal constant EPOCH = 7;

    function setUp() public {
        (attestor, attestorKey) = makeAddrAndKey("attestor");

        groth16 = new Groth16Verifier();
        verifier = new ZkViewPrivacyVerifier(address(groth16));

        vm.startPrank(owner);
        oracle = new ProofOfView(owner);
        oracle.setAttestor(attestor);
        oracle.setSplitter(splitter);
        oracle.setPrivacyVerifier(address(verifier));
        vm.stopPrank();
    }

    function _proof() internal pure returns (IViewPrivacyVerifier.Groth16Proof memory) {
        return IViewPrivacyVerifier.Groth16Proof({
            a: [
                0x1aad79d64e23f757a7768e3dab8013851d179a10daf4248b963dd5108a89e69e,
                0x22853eb6b5b5eb3fce934f3229315f7778a22027696c66214222c150a66b110e
            ],
            b: [
                [
                    0x1c6b3c5535e59a53f74c433cc5b2664216e8e00b6ec348cf7c2d74d3a2fb0335,
                    0x1e644c1cdf6400f0ee4bfa08453004fa7f08a17b5c412f5424e962b776cc65c2
                ],
                [
                    0x254677c7e914c54e323d6b9b51d258472d0ad502ee502a5f86e780d4e8b1c807,
                    0x145a1e0963826ed7e1a031b4f0fc0416e6d362f48feb8d7d05dd6d49bdbfd8f4
                ]
            ],
            c: [
                0x034b1aaed20d0f9c96c8ce5fe72d0615e1083ec1d1af4ecb6deab7be61317d3d,
                0x2c1a1ac334988dfec3bd8173ed611f3609b09b66d875398b35f44d13a59a7bec
            ]
        });
    }

    function _attestation() internal view returns (IProofOfView.ViewAttestation memory) {
        return IProofOfView.ViewAttestation({
            viewId: keccak256("zk-view-1"),
            advertiser: advertiser,
            creator: creator,
            commitment: COMMITMENT,
            nullifier: NULLIFIER,
            campaignId: CAMPAIGN_ID,
            weight: 5e18,
            epoch: uint64(EPOCH),
            deadline: uint64(block.timestamp + 1 hours)
        });
    }

    function _sign(IProofOfView.ViewAttestation memory a) internal view returns (bytes memory) {
        bytes32 digest = oracle.getAttestationDigest(a);
        (uint8 v, bytes32 r, bytes32 s) = vm.sign(attestorKey, digest);
        return abi.encodePacked(r, s, v);
    }

    /*//////////////////////////////////////////////////////////////
                           REAL PROOF TESTS
    //////////////////////////////////////////////////////////////*/

    function testRealProofVerifiesDirectly() public view {
        assertTrue(verifier.verifyView(_proof(), COMMITMENT, NULLIFIER, CAMPAIGN_ID, EPOCH));
    }

    function testConsumeAcceptsRealProofAndSpendsNullifier() public {
        IProofOfView.ViewAttestation memory a = _attestation();
        bytes memory sig = _sign(a);

        vm.prank(splitter);
        uint256 weight = oracle.consume(a, sig, _proof());

        assertEq(weight, a.weight);
        assertTrue(oracle.isConsumed(a.viewId));
        assertTrue(oracle.isNullifierSpent(NULLIFIER));
    }

    function testRevertsIfProofPublicSignalsTampered() public {
        // Flip the campaign the attestor signs to one the proof was not generated for. The signature still matches the
        // attestation, but the proof no longer satisfies the public signals, so the privacy gate has to reject it.
        IProofOfView.ViewAttestation memory a = _attestation();
        a.campaignId = 43;
        bytes memory sig = _sign(a);

        vm.prank(splitter);
        vm.expectRevert(ProofOfView.ProofOfView__InvalidProof.selector);
        oracle.consume(a, sig, _proof());
    }

    function testRevertsIfSameViewerProvesTwice() public {
        IProofOfView.ViewAttestation memory a = _attestation();
        bytes memory sigA = _sign(a);
        vm.prank(splitter);
        oracle.consume(a, sigA, _proof());

        // The same viewer proving again in the same campaign and epoch produces the same nullifier, so even a fresh
        // view id and a valid proof cannot get them counted twice.
        IProofOfView.ViewAttestation memory b = _attestation();
        b.viewId = keccak256("zk-view-2");
        bytes memory sigB = _sign(b);

        vm.prank(splitter);
        vm.expectRevert(abi.encodeWithSelector(ProofOfView.ProofOfView__NullifierUsed.selector, NULLIFIER));
        oracle.consume(b, sigB, _proof());
    }

    function testGetVerifierExposesGroth16() public view {
        assertEq(verifier.getVerifier(), address(groth16));
    }
}
